'use strict';
// Guided first-time setup - writes server/.env after asking a few questions.
// Run:  node setup.js      (no dependencies, works on macOS / Windows / Linux)
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');
const { loadEnv, ipv4Candidates } = require('./env');

const ENV_PATH = path.join(__dirname, '.env');
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
let closed = false;
rl.on('close', () => { closed = true; });
// Resolve with the default if the input stream ends mid-prompt (piped input,
// closed terminal) so setup always finishes and writes a valid .env.
const ask = (q, def) => new Promise((res) => {
  if (closed) return res(def || '');
  let done = false;
  const finish = (a) => { if (done) return; done = true; res((a == null ? '' : String(a)).trim() || def || ''); };
  rl.question(def ? `${q} [${def}]: ` : `${q}: `, finish);
  rl.once('close', () => finish(''));
});

async function main() {
  console.log('\n========================================');
  console.log('   SlimeWatch server - guided setup');
  console.log('========================================\n');

  // Preload any existing .env so re-running edits rather than blanks the config.
  const existed = fs.existsSync(ENV_PATH);
  if (existed) { loadEnv(ENV_PATH); console.log('Found an existing .env - press Enter to keep each current value.\n'); }
  const cur = (k) => process.env[k] || '';

  // ---- Token ----
  // Most people are JOINING someone else's fleet: they must paste the exact
  // token the relay owner gave them. Auto-generating here (the old default) was
  // a footgun -- pressing Enter minted a NEW token that didn't match the fleet.
  console.log('1) Fleet token - the shared secret for your fleet.');
  console.log('   JOINING someone\'s fleet? Paste the EXACT token they gave you (their relay USER_TOKEN).');
  console.log('   Every server + the app on one fleet use the SAME value.');
  console.log('   Starting your OWN brand-new relay from scratch? Type  new  to generate one.');
  let token = cur('SLIME_TOKEN') && cur('SLIME_TOKEN') !== 'change-me' ? cur('SLIME_TOKEN') : '';
  let tokAns = await ask('   Fleet token (paste it, or "new")', token);
  if (tokAns.toLowerCase() === 'new') {
    tokAns = crypto.randomBytes(20).toString('hex');
    console.log('   -> Generated a NEW fleet token: ' + tokAns);
    console.log('      Use this SAME value as your relay USER_TOKEN and in the app.');
  }
  token = tokAns;

  // ---- Relay URL ----
  console.log('\n2) Relay URL - where this server registers. The relay owner gives you this,');
  console.log('   e.g. https://slime-relay.THEIR-NAME.workers.dev  (do NOT deploy your own).');
  console.log('   Leave blank only to run standalone (no dashboard / no fleet).');
  const relay = (await ask('   RELAY_URL', cur('RELAY_URL'))).replace(/\/+$/, '');

  // -- Name --
  console.log('\n3) Friendly name shown on the dashboard.');
  const name = await ask('   SERVER_NAME', cur('SERVER_NAME') || os.hostname());

  // -- Port --
  const port = await ask('\n4) Port to listen on', cur('PORT') || '8787');

  // -- Public address --
  console.log('\n5) How the Apple TV / app reaches THIS machine.');
  const cands = ipv4Candidates(port);
  if (cands.length) {
    console.log('   Detected addresses on this machine:');
    cands.forEach((c, i) => console.log(
      `     [${i + 1}] ${c.url}   (${c.iface}, ${c.kind}${c.virtual ? ', virtual - usually NOT reachable' : ''})`));
    console.log('     [0] auto-detect each start (fine on a single home network)');
  }
  const pick = await ask('   Choose a number, or paste a full http://...:port address', cur('PUBLIC_ADDRESS') || '0');
  let publicAddr = '';
  if (/^\d+$/.test(pick)) {
    const n = Number(pick);
    if (n >= 1 && n <= cands.length) publicAddr = cands[n - 1].url;   // n===0 -> blank (auto)
  } else if (pick) {
    publicAddr = pick.startsWith('http') ? pick : `http://${pick}`;
  }

  const body =
`# SlimeWatch server config - generated by setup.js. Safe to edit by hand.
# .env is gitignored - never commit it.

SLIME_TOKEN=${token}
PORT=${port}
RELAY_URL=${relay}
PUBLIC_ADDRESS=${publicAddr}
SERVER_NAME=${name}

# -- Optional extras --
DIRECT_RESOLVER=${cur('DIRECT_RESOLVER')}
SLIME_SUBS_KEY=${cur('SLIME_SUBS_KEY')}
`;
  fs.writeFileSync(ENV_PATH, body);
  rl.close();

  console.log(`\n[OK]  Wrote ${ENV_PATH}`);
  console.log('\nNext:');
  console.log('   - node doctor.js      - verify everything is good to go');
  console.log('   - ./start.sh          - start the server   (Windows: double-click start.bat)');
  if (relay) console.log(`   - Dashboard:  ${relay}/?key=<your ADMIN token>`);
  console.log('');
}

main().catch((e) => { console.error('setup failed:', e.message); rl.close(); process.exit(1); });
